### PR TITLE
User Interface

### PR DESCRIPTION
**Pull request by joelethan**
_**What does this PR do?**_
Create a User Interface for the Fast-Food-Fast restaurant

_**Description of Task to be completed?**_
Create Signup and Signin pages so that users can create accounts and be able to login into the app
Create a page where the user should be able to view the available food and make an Order for food
Create a page where the admin can manage the status of an Order from the user
Create a history page where the user can view the food previous ordered for
Create a forgot password page where the User can reset their password incase it is forgotn

_**What are the relevant pivotal tracker stories?**_
#160423068
#160422997
#160422835
#160422896
#160489574

_**GitHub-Pages link**_
https://joelethan.github.io/Fast-Food-Fast/UI/

### CODE REVIEW

**Comment by walimike** [comment]
hey man well done, please attach a link to your gh-pages, plus I think commit messages are meant to be in present continuous

**Comment by sekayasin** [comment]
@joelethan bravo bro, quick one, on the commit messages, also add the **[Delivers|Finishes|Fixes #PivtoalTrackerStoryID]** , on the signup page , u ave some typo - **creacte an ccount**

**Comment by Luleherll** [comment]
let me tell you what someone said on my UI to fix. Make sure you link every link you put on your ui redirect to what its supposed to do. have seen one to fix ```order```. Otherwise, good job. its not bad

**Comment by mozzy22** [comment]
its cool , i like the responsiveness , and the validation . good to go. 
the only issue i s, find a way of limiting the Client user to acces the admin page , and only the admin shud acces the admin page. meaning remove the admin link from the client order page , only the admin shud acces it . u can use java script to do that

**Comment by krmroland** [comment]
@mozzy22, In my opinion, limiting  who should see which page is  not `javascript's role`  but maybe `jwt tokens`, and even if it was, challenge 1 still makes it clear that 
>You are not implementing the core functionality yet, you are only building the User
Interface elements, pages, and views

@joelethan You may not want to  waste your precious time implementing something like this in Javascript, If I where you, I would proceed to do other things that really matter

**Comment by Phionamary** [comment]
@joelethan Good work so far. 
I also must commend you on the way you write the description for your PR,  it's really clear.  
For now,  i think do not put so much pressure on your self,  trying to implement functionalities,  as long as you have the required pages. 
Good work on what you have done so far

**Comment by joelethan** [comment]
m

**Comment by katunold** [comment]
Great work, Your images don't take ages to load

**Comment by jeanjoe** [comment]
Nice work, Well organized

**Pull request merged**
